### ISSUE TITLE
get_Enu() : anita_earthmodel2

### ISSUE THREAD

**Issue by molmedon** [rprechelt/nusim#3]
check that get_Enu() is sensible

**Comment by lukashertrich** [comment]
This function uses a von [Neumann rejection method](http://www.phys.hawaii.edu/~varner/PHYS305-Spr12/VonNeumann_background.html) to generate points that lie within the area under the curve described by the polynomial coefficients for [Engel, Seckel, Stanev](https://arxiv.org/abs/astro-ph/0101216).

The method first randomly selects an energy in the valid range, then compares a random flux to the resulting ESS flux for that energy. Flux in excess of ESS gets rejected. The result is that, on the whole, the flux of the neutrinos is properly distributed.

**Comment by lukashertrich** [comment]
This is the cosmogenic flux before passage through Earth for a sample of 10^5 neutrinos:
![flux_distribution](https://user-images.githubusercontent.com/10600695/36819854-36a867f6-1c8f-11e8-972a-8daf9d556df8.png)
