### ISSUE TITLE
get_nadir_angle() : anita_earthmodel2

### ISSUE THREAD

**Issue by molmedon** [rprechelt/nusim#4]
check that get_nadir_angle() is sensible

**Comment by lukashertrich** [comment]
This function returns acos(drand48()), which provides the correct distribution of angles [0 : pi/2] for the nadir when the azimuth is randomized in a later module (outside anita_earthmodel2.c).

The code assumes the following: [Uniform Sphere Point Picking](http://mathworld.wolfram.com/SpherePointPicking.html)
