### ISSUE TITLE
get_Lint_nc(double E, double cross_section_factor) : anita_earthmodel2

### ISSUE THREAD

**Issue by molmedon** [rprechelt/nusim#6]
check that get_Lint_nc(double E, double cross_section_factor) is sensible

**Comment by lukashertrich** [comment]
Function is sensible. The returned value isn't a direct interaction length, but rather the product of interaction length and a (negative) logarithmically distributed random number in the range 0 to infinity. The calling function which actually performs integration along the track uses this value to simulate flux attenuation per neutrino.
