### ISSUE TITLE
get_firn_dens(double depth) : anita_earthmodel2

### ISSUE THREAD

**Issue by molmedon** [rprechelt/nusim#7]
check that get_firn_dens() is sensible

**Comment by lukashertrich** [comment]
Function appears to be sensible. Cursory searches indicate that firn density ranges around 550 to 830 kg per cubic meter. The code starts at 680 kg per m^3 (0.68 g/cm^3) and stacks on density based on a gnuplot fit done by Peter. We may want to look at exponential ice density models to verify that the coefficients are reasonable, though BEDMAP does provide this kind of data as well.
