### ISSUE TITLE
integrate_Lint(double uA, double LL)

### ISSUE THREAD

**Issue by molmedon** [rprechelt/nusim#9]
check that integrate_Lint(double uA, double LL) is sensible

**Comment by lukashertrich** [comment]
As an input, this function takes the nadir angle of a simulated neutrino, and an interaction length which has been multiplied with -ln(random number from 0 to 1). The negative natural log is used to generate a distribution [0 to infinity] that allows exponential decay of flux to be evaluated per neutrino. If integrate_Lint doesn't accumulate the interaction length during traversal through the ice it tries again. Accumulation too early (in Earth) or ice gets returned as a depth (rejected by calling function).
